name: sendeach_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  permission_handler: ^10.2.0
  get: 4.6.5
  flutter:
    sdk: flutter
  sms_sender:
    path: /Users/prathamsarankar/AndroidStudioProjects/sms_sender
  google_fonts: ^4.0.3
  fluttertoast: ^8.2.1
  device_info_plus:
  get_storage: ^2.1.1
  firebase_messaging: ^14.3.0
  loading_indicator: ^3.1.0
  animated_splash_screen: ^1.3.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

